### ISSUE TITLE
Refactor CRUD under store namespace

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/genotype-api#91] opened 2024-03-07 07:50 UTC

**Comment by ChrOertlin** [comment] 2024-03-07 15:22
duplicate of #90 ?

**Comment by henrikstranneheim** [comment] 2024-03-08 09:15
No, just moving everything under a store/database directory. Which you are fixing in the ongoing PR 👍

**Closed** 2024-03-12 14:28 UTC
Labels: Effort S, Enhancement, Gain M, Urgency S
